name: vanilla
description: Vanilla Dating App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-30.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.4
  firebase_auth: ^4.1.0
  firebase_storage: ^11.0.3
  firebase_core: ^2.1.1
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  google_sign_in: ^5.4.2
  email_validator: ^2.1.17
  cloud_firestore: ^4.0.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  fluttertoast: ^8.1.1
  http: ^0.13.5
  flutter_facebook_auth: ^5.0.1
  flutter_secure_storage: ^6.0.0
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/
  #   - images/a_dot_ham.jpeg



  fonts:
     - family: Proxima Nova
       fonts:
         - asset: fonts/Proxima-Nova-Alt-Bold.otf
         - asset: fonts/Proxima-Nova-Alt-Light.otf
         - asset: fonts/Proxima-Nova-Alt-Thin.otf
         - asset: fonts/Proxima-Nova-Black.otf
         - asset: fonts/Proxima-Nova-Bold.otf
         - asset: fonts/Proxima-Nova-Extrabold.otf
         - asset: fonts/Proxima-Nova-Thin.otf
         - asset: fonts/Proxima-Nova-Regular.otf
  #      - asset: fonts/Schyler-Italic.ttf
  #         style: italic
